openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
   Swagger ve api cua facebook
  termsOfService: http://localhost:8000/v1/api
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://localhost:8000/v1/api
servers:
  - url: http://localhost:8000/v1/api
tags:
  - name: users
    description: Tag api users
    externalDocs:
      description: Find out more
      url: http://localhost:8000/v1/api
 
paths:
  /user/login:
    post:
      tags:
        - users
      summary: Login user
      description: Dang nhap vao he thong
      operationId: loginUser
      requestBody:
        description: Login to the system  
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: test1@gmail.com
                password:
                  type: string
                  example: dellcomk
        required: true
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: OK
                  status:
                    type: integer
                    example: 200
                  metadata:
                    type: object
                    properties:
                      user:
                        type: object
                        properties:
                          _id:
                            type: string
                            example: 6678d83993d871fd97dfedb8
                          email:
                            type: string
                            example: test1@gmail.com
                          avatar:
                            type: string
                            example: https://firebasestorage.googleapis.com/v0/b/project-8eefd.appspot.com/o/avatars%2Ff94dc1d0-6937-4255-8871-17f99e023593?alt=media&token=dfd1f7ce-7997-40f4-9f94-61e569c1b719
                          firstName:
                            type: string
                            example: test
                          lastName:
                            type: string
                            example: 1
                      tokens:
                        type: object
                        properties:
                          accessToken:
                            type: string
                            example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc4ZDgzOTkzZDg3MWZkOTdkZmVkYjgiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImlhdCI6MTcyMjU4ODIwNywiZXhwIjoxNzIzMTkzMDA3fQ.1P0BQZ9LLzCYEjCrS3wtpCNny166OQKmfFzrdZZHJKY
                          refreshToken:
                            type: string
                            example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njc4ZDgzOTkzZDg3MWZkOTdkZmVkYjgiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImlhdCI6MTcyMjU4ODIwNywiZXhwIjoxNzIzMTkzMDA3fQ.jJEcaHfU7BfZQZc-m_O7w0BLTqhau8qc2cOhqtu5eWs
        '400':
          description: Invalid input
        '422':
          description: Validation exception
      security:
        - apiKey: []

components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: x-api-key
      in: header
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        petId:
          type: integer
          format: int64
          example: 198772
        quantity:
          type: integer
          format: int32
          example: 7
        shipDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          example: approved
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean
      xml:
        name: order
  